name: HACS

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/action@v4
        with:
          category: plugin
